platforma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('universystem.urls')),
    path('', include("django.contrib.auth.urls")),



    # path('home/', include('homepage.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

universystem/urls.py
from django.urls import path
from . import views, views_auth
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

app_name = 'universystem'

urlpatterns = [
    path('', views.homepage, name="home"),
    path('registration/', views_auth.registration, name='register'),
    path('register/success', views_auth.success, name='success'),
    path('register/token', views_auth.token_send, name='token_send'),
    path('register/verify/<auth_token>', views_auth.verify, name='verify'),
    path('register/error', views_auth.error, name='error'),
    path('login/', views_auth.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.view_profile, name='profile'),
    path('topics/', views.topics, name='topics'),
    path('article/<slug:slug>/', views.article_list, name='article'),
    path('lesson/<slug:slug>/', views.post_detail, name='post_detail'),
    path('runcode/', views.runcode, name="runcode"),
    path('search/', views.search_venues, name="search"),
    path('quiz/', login_required(views.QuizListView.as_view()), name="main-quiz"),
    path('quiz/<int:pk>/', views.quiz_view, name="quiz-view"),
    path('quiz/<int:pk>/save/', views.save_quiz_view, name="save-view"),
    path('quiz/<int:pk>/data/', views.quiz_data_view, name="quiz-data-view"),
    path('quiz/exam', views.exam, name="exam"),

    path('profile/edit', views.edit_profile, name="edit_profile"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

universystem/forms.py
from .models import Chapters, Profile, Lectures, LecturesText, Image
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Chapters, Profile, Lectures, LecturesText, Image


class CustomUserCreationForm(UserCreationForm): 
    username = forms.CharField(label='username', min_length=5, max_length=150) 
    email = forms.EmailField(label='email') 
    password1 = forms.CharField(label='password', widget=forms.PasswordInput) 
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput) 
 
    def username_clean(self): 
        username = self.cleaned_data['username'].lower() 
        new = User.objects.filter(username = username) 
        if new.count(): 
            raise ValidationError("User Already Exist") 
        return username 
 
    def email_clean(self): 
        email = self.cleaned_data['email'].lower() 
        new = User.objects.filter(email=email) 
        if new.count(): 
            raise ValidationError(" Email Already Exist") 
        return email 
 
    def clean_password2(self): 
        password1 = self.cleaned_data['password1'] 
        password2 = self.cleaned_data['password2'] 
 
        if password1 and password2 and password1 != password2: 
            raise ValidationError("Password don't match") 
        return password2 
 
    def save(self, commit = True): 
        user = User.objects.create_user( 
            self.cleaned_data['username'], 
            self.cleaned_data['email'], 
            self.cleaned_data['password1'] 
        ) 
        return user 


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class ChaptersForm(forms.ModelForm):
    class Meta:
        model = Chapters
        fields = ['title', 'description']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Введите пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data        
        if cd['password'] != cd['password2']:            
            raise forms.ValidationError('Passwords don\'t match.')        
        return cd['password2']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['photo']


class LecturesForm(forms.ModelForm):

    class Meta:
        model = Lectures
        fields = ['name', 'value']


class LecturesTextForm(forms.ModelForm):

    class Meta:
        model = LecturesText
        fields = ['lectures_id', 'title', 'text', 'photo']


class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ('title', 'image')

universystem/views.py
from django.http import JsonResponse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView

from .forms import UserUpdateForm, ProfileUpdateForm
from .models import Answer, Question, Result, Quiz, Chapters, Article


class QuizListView(ListView):
    model = Quiz
    template_name = "quiz_main.html"


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quiz.html', {'obj': quiz})


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    # print(request.POST)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.numbers_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})


@login_required(login_url="/login/")
def view_profile(request):
    result = Result.objects.filter(user=request.user)
    context = {
        'user': request.user,
        'result': result
    }
    return render(request, 'ProfileView.html', context)


@login_required(login_url="/login/")
def edit_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Аккаунт жаңа баптаулары сақталды')
            return redirect('universystem:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user': request.user,
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'editprofile.html', context)


@login_required(login_url="/login/")
def runcode(request):
    return render(request, 'compiler.html')


def homepage(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        message = request.POST.get('message')
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email, 'pythonplatformkz@gmail.com']
        contact_message = "%s: %s via %s" % (
            name,
            message,
            email)

        if subject:
            send_mail(
                subject,
                contact_message,
                from_email,
                to_email,
                fail_silently=False,
            )

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('universystem:topics')

        else:
            messages.info(request, 'Қате логин терілді...')
    return render(request, 'index.html')


@login_required(login_url="/login/")
def article_list(request, slug):
    article = get_object_or_404(Article, slug=slug)
    context = {
        'article': article,
        'title': article.title,
        'id_selected': article.article_id,
    }
    return render(request, 'chapter.html', context)


@login_required(login_url="/login/")
def search_venues(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        articles = Article.objects.filter(
            Q(title__icontains=searched) |
            Q(topic1=searched) |
            Q(topic2=searched) |
            Q(topic3=searched) |
            Q(body1__icontains=searched) |
            Q(body2__icontains=searched) |
            Q(body3__icontains=searched)
        )

        return render(request, "search_venues.html", {'searched': searched, 'articles': articles})
    else:
        return render(request, "search_venues.html", {})


@login_required(login_url="/login/")
def topics(request):
    topic = Article.objects.all()
    context = {'topics': topic}
    return render(request, "topics.html", context)


def chapters(request):
    chapter = Chapters.objects.all()
    return render(request, "topics.html")


def post_detail(request, slug):
    post = Article.objects.get(slug=slug)
    context = {'post': post}
    return render(request, "lesson.html", context)


@login_required(login_url="/login/")
def exam(request):
    return render(request, "exam.html")

universystem/templates/ProfileView.html
{% extends 'base.html' %}


{% load static %}

<link rel="stylesheet" href="{% static 'assets/css/Account-setting-or-edit-profile.css' %}">
{% block content %}
 {% if user.is_authenticated %}
 <style>
    a:link {
    color: #7971ea;
    text-decoration: none;
    }
    
    /* visited link */
    a:visited {
    color: #7971ea;
    }
    
    /* mouse over link */
    a:hover {
    color: black;
    }
    
    /* selected link */
    a:active {
    color: black;
    }
    a.course{
    color: #7971ea;
    }
    .btn.btn-primary{
        color: white;
        background-color: #7971ea;
    }
    .user-avatar{
        margin-top: 1rem;
        border-radius: 50%;
        width: 200px;
        height: 120px;
        margin-left: 2rem;
        display: block;
    margin: 0 auto;
    }
    img{
        border-radius: 50%;
        width: 100%;
        height: auto;
        width: 150px;
  height: 150px;
  border-radius: 50%;
  margin: 20px;

  object-fit: cover;
  object-position: center right;
    }
    
    .user-avatar{
        width: 180px;
        height: 180px;
    }
   
    #account{
        border-radius: 50px;
        border: none; 
        padding: 10px;
    }
    .breadcrumb{
        background-color: white; 
        font-size: 18px; 
        margin-top: 4rem;

    }
    .user-name{
        padding-top: 30px;
    }


    @media all and (max-width: 1400px){
        .breadcrumb{
        background-color: white; 
        font-size: 16px; 
        margin-top: 2rem;
        margin-bottom: -0.5rem;
        
        }
        .user-avatar{
        width: 150px;
        height: 150px;
        display: block;
    margin: 0 auto;
    }
    .about h5{
        font-size: 16px;
    }
    .about p{
        font-size: 14px;
    }
    }
    @media all and (max-width: 1200px){
        .breadcrumb{
        background-color: white; 
        font-size: 16px; 
        margin-top: 2rem;
        margin-bottom: -0.5rem;
        
        }
        .user-avatar{
        width: 120px;
        height: 120px;
        display: block;
    margin: 0 auto;
    }
    .user-name{
        margin-top: -1rem;
        font-size: 16px;
    }
    .about h5{
        font-size: 16px;
    }
    .about p{
        font-size: 14px;
    }
    }
    @media all and (max-width: 995px){
        .account-settings{
        text-align: center;
        
    }
    img{
        width: 120px;
        height: 120px;
        display: block;
    margin: 0 auto;
    }
    }


    @media all and (max-width: 500px){
        .breadcrumb{
        background-color: white; 
        font-size: 14px; 
        margin-top: 1.5rem;
        margin-bottom: -0.5rem;
    }
    .user-profile{
        width: 300px;
        height: 300px;
    }
    .user-avatar{
        width: 100px;
        height: 100px;
        margin-left: 2rem;
        
    }
    
    .user-name{   
        margin-top: 1rem;
        font-size: 18px;
    }
    .about{
        margin-top: -5rem;
    }
    .about h5{
        font-size: 16px;
    }
    .about p{
        font-size: 14px;
    }
    #account{
        border-radius: 50px;
        border: none; 
        font-size: 14px;
        padding: 10px;
    }
    .account-settings{
        margin-left: 3.8rem;
        text-align: justify;
    }
    }
    </style>
 <div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'universystem:topics' %}" >Курс</a></li>
       <li class="breadcrumb-item"><a href="{% url 'universystem:profile' %}" >Жеке кабинет</a></li>
   
   </ol>

   
<div class="container py-4 py-xl-5" id="section-1"><div class="container">

    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="user-avatar">
                       

{#                         <img src="{% if user.profile.photo %}{{user.profile.photo.url}}{% else %}{% static 'media/images/profile/pfp.png' %}{% endif %}"  id="pfp" alt="profilephoto" class="rounded-circle">#}

                    </div>
                    <h5 class="user-name">Тіркелгі аты: {{ user.username }}</h5>
                    <h6 class="user-email">Эл.пошта: {{ user.email }}</h6>
                </div>
                <div class="about" >
                    <h5>Тіркелу күні:</h5>
                    <p>{{user.date_joined}}</p>
                </div>
                <a href="{% url 'universystem:edit_profile' %}" class="btn btn-primary" id="account">Аккаунт баптаулары</a>
                {% if messages %}
                {% for message in messages %}   
                <div class="alert alert-info">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="row gutters">
                <!-- <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary" style="color: #7971ea;">Қаралған тақырыптар: </h6>
                </div> -->
               
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h5 class="mt-3 mb-2" style="color: #7971ea;">Тест нәтижелері:</h5>
                   <ol> {% for r in result %}
                    
                        <li>{{r.quiz.name }}: {{r.score}} %</li>
                    
                    {% endfor %}</ol>
                    <a class="btn btn-primary" style=" float: right; padding: 0.5rem 2.5rem; color:white; text-decoration: none; background-color: #7971ea; border-radius:50px;border: none; margin-right: 2rem; position: absolute;
                    right:    0;
                    bottom:   0; " href="{% url 'universystem:main-quiz' %}">Тестке көшу</a>

                </div>
                
            </div>
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        <!-- <button type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</button> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 {% else %}
  <p>login to view</p>

  {% endif %}

{% endblock %}  

universystem/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Python</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Articles-Cards.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navbar-Centered-Links.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Articles-Cards.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <style>
        body{
            overflow-x: hidden; 
        }
       
    </style>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md py-3" >
        <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'universystem:topics' %}">
            <span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon">
                <i class="fab fa-python"></i>
            </span>
            <span>Python</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
            <ul class="navbar-nav me-auto">
                <!-- <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:topics' %}">Курс</a></li> -->
                <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:profile' %}">Жеке кабинет</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:runcode' %}">Компилятор</a></li>
  
  
                <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:logout' %}">Шығу</a></li>
                <li class="nav-item"></li>
            </ul>
            
            <form class="form-inline my-2 my-lg-0" action="{% url 'universystem:search'%}" method="post">
                {% csrf_token %}
                
                <input class="form-control mr-sm-2" type="search" placeholder="Іздеу..." aria-label="Search" name="searched" style="border-radius: 50px; padding: 5.5px; border-color: #7971ea;">
                <button class="btn btn-primary" id="search" type="submit">Іздеу</button>
            </form>
        </div>
    </div>
      </nav>

    <!-- <nav class="navbar navbar-light navbar-expand-md py-3" >
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'universystem:topics' %}">
            <span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon">
                <i class="fab fa-python"></i>
            </span>
            <span>Python</span>
        </a>
        <button data-bs-toggle="collapse" type="button" class="navbar-toggler collapsed hidden-lg-up ml-auto float-xs-right" data-bs-target="#navcol-1">
            <span class="visually-hidden">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
            

        </button>
            <ul class="navbar-nav">
                <li class="nav-item"></li>
                <li class="nav-item"></li>
                <li class="nav-item"></li>
            </ul>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:profile' %}">Жеке кабинет</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:runcode' %}">Компилятор</a></li>


                    <li class="nav-item"><a class="nav-link active" href="{% url 'universystem:logout' %}">Шығу</a></li>
                    <li class="nav-item"></li>
                </ul>
                <form action="{% url 'universystem:search'%}" method="post">
                    {% csrf_token %}
                    <input type="search" placeholder="Іздеу..." aria-label="Search" name="searched" style="border-radius: 50px; padding: 5.5px; border-color: #7971ea;">
                    <button class="btn btn-primary" id="search" type="submit">Іздеу</button>
                </form>
            </div>
        </div>
    </nav> -->
{% block content %}
 
{% endblock %}         
<footer class="text-center py-4">
    <div class="container">
        <div class="row row-cols-1 row-cols-lg-3">
            <div class="col">
                
            </div>
            <div class="col">
                <p class="text-muted my-2">Copyright&nbsp;© 2022&nbsp;</p>
            </div>
            
        </div>
    </div>

</footer>
<script>
    
    document.getElementById("id_q").value = "{{query}}"
</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/pagination.js' %}"></script>
</body>
</html>

universystem/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container py-4 py-xl-5">
  <ol class="breadcrumb" style="background-color: white; font-size: 16px;">
    <li class="breadcrumb-item"><a href="#"><span>Home</span></a></li>
    <li class="breadcrumb-item"><a href="#"><span>Library</span></a></li>
    <li class="breadcrumb-item"><a href="#"><span>Data</span></a></li>
</ol>
  <div class="row mb-5">
      <div class="col-md-8 col-xl-6 text-center mx-auto">
          <h2 class="font-weight-bold"><a href="http://127.0.0.1:8000/lessons/1">Python тілі негіздері, мәліметтер түрлері және өңдеу</a><br></h2>
          <p class="w-lg-50">{{ lecturesone.name }}</p>
          
      </div>
  </div>

  


  <div class="card">
      <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs" id="lesson-list">
              <li class="nav-item"><a class="nav-link active" href="#about" role="tab" data-toggle="tab"><span style="text-decoration: none;">Description</span></a></li>
              <li class="nav-item"><a class="nav-link" href="#lessons" role="tab" data-toggle="tab">Тақырып</a></li>
              <li class="nav-item"><a class="nav-link" href="#de" role="tab" data-toggle="tab">Third Item</a></li>
          </ul>
      </div>
      <div class="tab-content">
        <div role="tabpanel"class="tab-pane active" id="about">
          <div class="card-body">
            <h4 class="card-title">Title</h4>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum, nam.</p>
          </div>
        </div>
        <div role="tabpanel"class="tab-pane" id="lessons">
          <div class="card-body">
            <h4 class="card-title">Title</h4>
            <ul class="list-group">
                <li class="list-group-item"><span><a href="{% url 'universystem:article' %}"><span style="text-decoration: underline;">Python тілінің мәліметтер типтері мен құрылымы</span></a><br></span></li>
                <li class="list-group-item"><span><a href="http://127.0.0.1:8000/lessons/1"><span style="text-decoration: underline;">Python программалау тілі туралы жалпы мағлұматтар</span></a><br></span></li>
                <li class="list-group-item"><span><a href="http://127.0.0.1:8000/lessons/1"><span style="text-decoration: underline;">Python тілінде программалау құралдары</span></a><br></span></li>
            </ul>
        </div>
        </div>
        <div role="tabpanel"class="tab-pane" id="de">
          <div class="card-body">
            <h4 class="card-title">Title</h4>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore quo beatae dicta non vel ea.</p>
          </div> 
        </div>
      </div>
      
</div>  

<style>
  /* unvisited link */
  a:link {
    color: black;
text-decoration: none;
  }
  
  /* visited link */
  a:visited {
    color: #7971ea;
  }
  
  /* mouse over link */
  a:hover {
    color: black;
  }
  
  /* selected link */
  a:active {
    color: blue;
  }
  </style>

{% endblock %}  







{% for topic in topics %}
<div class="col">
    <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;" src="{{topic.image.url}}" alt="{{topic.slug}}">
        <div class="card-body p-4" style="height: 334.391px;">
            <p class="text-primary card-text mb-0">Article</p>
            <h4 class="card-title"><a href="/article/{{topic.slug}}">{{topic.article_id  }}</a><br></h4>
            <p class="card-text" style="font-size: 18px;"><a href="{{topic.get_absolute_url_1}}">1. {{topic.topic1}}</a><br><a href="{{topic.url}}">2. {{topic.topic2}}</a><br><a href="{{topic.url}}">3. {{topic.topic3}}</a><br><br></p>
        </div>
    </div>
</div>

{% endfor %}

universystem/templates/exam.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="authincation h-100" style="background-color: #7971ea;">
    <div class="container h-100">
        <div class="row justify-content-center h-100 align-items-center">
            
                        <div class="card" >
                            <div class="card-body align-items-center" >
                              <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdD-dmCrTimfytAOZK44C0Ko_U3KDjoreKVV1EOG2dH9v4zpw/viewform?embedded=true"  frameborder="0" marginheight="0" marginwidth="0">Загрузка…</iframe>
                </div>
            
               
            </div>
        </div>
    </div>
</div> 
<style>
  .card{
    margin: 4rem;
    width:700px; 
    height:870px;
     box-shadow: rgba(0, 0, 0, 0.25) 0px 54px 55px,
      rgba(0, 0, 0, 0.12) 0px -12px 30px,
       rgba(0, 0, 0, 0.12) 0px 4px 6px, 
       rgba(0, 0, 0, 0.17) 0px 12px 13px,
        rgba(0, 0, 0, 0.09) 0px -3px 5px;}
 iframe{
  width:640px;
  height:828px;
 }
        @media all and (max-width: 500px){
          .card{
         
        margin: 1rem -0.2rem;
         padding: 0.5rem 0.5rem;
          width: 390px; 

          }
          iframe{
            margin-left: -1.5rem;
  width:390px;
  height:828px;
 }
        }
</style>

{% endblock %}